WebBooks/WebBooks/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from catalog import urls as cat_urls


urlpatterns = [
    path("catalog/", include(cat_urls)),
    path("admin/", admin.site.urls),
    # path("password_reset/action", mypassaction),
    path("", include("django.contrib.auth.urls")),
]

WebBooks/catalog/urls.py
from xml.etree.ElementInclude import include
from django.urls import path, re_path

import django.contrib.auth.urls

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("authors_add/", views.authors_add, name="authors_add"),
    path("authors_add/edit1/<int:id>", views.edit1, name="edit1"),
    path("authors_add/create/", views.create, name="create"),
    path("authors_add/delete/<int:id>/", views.delete, name="delete"),
    re_path(r"^books/$", views.BookListView.as_view(), name="books"),
    re_path(r"book/(?P<pk>\d+)$", views.BookDetailView.as_view(), name="book-detail"),
    re_path(r"^authors/$", views.AuthorListView.as_view(), name="authors"),
    re_path(
        r"^mybooks/$",
        views.LoanedBooksByUserListView.as_view(),
        name="my-borrowed",
    ),
]

WebBooks/catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date


class Genre(models.Model):
    name = models.CharField(
        max_length=200,
        help_text="Введите жанр книги",
        verbose_name="Жанр книги",
    )

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(
        max_length=20,
        help_text="Введите язык книги",
        verbose_name="Язык книги",
    )

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(
        max_length=100,
        help_text="Введите имя автора",
        verbose_name="Имя автора",
    )
    last_name = models.CharField(
        max_length=100,
        help_text="Введите фамилию автора",
        verbose_name="фамилию автора",
    )
    date_of_birth = models.DateField(
        help_text="Введите дату рождения",
        verbose_name="Дата рождения",
        null=True,
        blank=True,
    )
    date_of_death = models.DateField(
        help_text="Введите дату смерти",
        verbose_name="Дата смерти",
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.last_name


class Book(models.Model):
    title = models.CharField(
        max_length=200,
        help_text="Введите название книги",
        verbose_name="Название книги",
    )
    genre = models.ForeignKey(
        "Genre",
        on_delete=models.CASCADE,
        help_text="Выберите жанр для книги",
        verbose_name="Жанр книги",
        null=True,
    )
    language = models.ForeignKey(
        "Language",
        on_delete=models.CASCADE,
        help_text="Выберите язык книги",
        verbose_name="Язык книги",
        null=True,
    )
    author = models.ManyToManyField(
        "Author",
        help_text="Выберите автора книги",
        verbose_name="Автор книги",
    )
    summary = models.TextField(
        max_length=1000,
        help_text="Введите краткое описание книги",
        verbose_name="Аннотация книги",
    )
    isbn = models.CharField(
        max_length=13,
        help_text="Должно содержать 13 символов",
        verbose_name="ISBN книги",
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book-detail", args=[str(self.id)])

    def display_author(self):
        return ", ".join([author.last_name for author in self.author.all()])

    display_author.short_description = "Авторы"


class Status(models.Model):
    name = models.CharField(
        max_length=20,
        help_text="Введите статус экземпляра книги",
        verbose_name="Статус экземпляра книги",
    )

    def __str__(self):
        return self.name


class BookInstance(models.Model):

    book = models.ForeignKey(
        "Book",
        on_delete=models.CASCADE,
        null=True,
    )
    inv_nom = models.CharField(
        max_length=20,
        null=True,
        help_text="Введите инвентарный номер экземпляра",
        verbose_name="инвентарный номер",
    )
    imprint = models.CharField(
        max_length=200,
        help_text="Введите издательство и год выпуска",
        verbose_name="Издательство",
    )
    status = models.ForeignKey(
        "Status",
        on_delete=models.CASCADE,
        null=True,
        help_text="Изменить состояние экземпляра",
        verbose_name="Статус экземпляра книги",
    )
    due_back = models.DateField(
        null=True,
        blank=True,
        help_text="Введите конец срока статуса",
        verbose_name="Дата окончания статуса",
    )
    borrower = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Заказчик",
        help_text="Выберите заказчика книги",
    )

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    def __str__(self):
        return "%s %s %s" % (self.inv_nom, self.book, self.status)

WebBooks/catalog/forms.py
from django import forms

from datetime import date


class AuthorsForm(forms.Form):
    first_name = forms.CharField(label="Имя автора")
    last_name = forms.CharField(label="Фамилия автора")

    date_of_birth = forms.DateField(
        label="Дата рождения",
        initial=format(date.today()),
        widget=forms.widgets.DateInput(attrs={"type": "date"}),
    )
    date_of_death = forms.DateField(
        label="Дата смерти",
        initial=format(date.today()),
        widget=forms.widgets.DateInput(attrs={"type": "date"}),
    )

WebBooks/catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from .models import Book, Author, BookInstance
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import AuthorsForm

# Create your views here.


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    num_instances_available = BookInstance.objects.filter(status__exact=2).count()

    num_authors = Author.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1
    context = {
        "num_books": num_books,
        "num_instances": num_instances,
        "num_instances_available": num_instances_available,
        "num_authors": num_authors,
        "num_visits": num_visits,
    }
    return render(request, "catalog/index.html", context=context)


class BookListView(generic.ListView):
    model = Book
    paginate_by = 3


class BookDetailView(generic.DetailView):
    model = Book


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 4


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """
    Универласьный класс представления спика книг,
    находящихся в заказе у текущего пользователя.
    """

    model = BookInstance
    template_name = "catalog/bookinstance_list_borrowed_user.html"
    paginate_by = 10

    def get_queryset(self):
        return (
            BookInstance.objects.filter(borrower=self.request.user)
            .filter(status__exact="2")
            .order_by("due_back")
        )


def authors_add(request):
    author = Author.objects.all()
    authorsform = AuthorsForm()
    context = {
        "form": authorsform,
        "author": author,
    }
    return render(request, "catalog/authors_add.html", context=context)


def create(request):
    if request.method == "POST":
        author = Author()
        author.first_name = request.POST.get("first_name")
        author.last_name = request.POST.get("last_name")
        author.date_of_birth = request.POST.get("date_of_birth")
        author.date_of_death = request.POST.get("date_of_death")
        author.save()
        return HttpResponseRedirect("/catalog/authors_add/")


def delete(request, id):
    try:
        author = Author.objects.get(id=id)
        author.delete()
        return HttpResponseRedirect("/catalog/authors_add/")
    except Author.DoesNotExist:
        return HttpResponseNotFound("Автор не найден")


def edit1(request, id):
    author = Author.objects.get(id=id)
    if request.method == "POST":
        author.first_name = request.POST.get("first_name")
        author.last_name = request.POST.get("last_name")
        author.date_of_birth = request.POST.get("date_of_birth")
        author.date_of_death = request.POST.get("date_of_death")
        author.save()
        return HttpResponseRedirect("/catalog/authors_add/")
    else:
        return render(request, "catalog/edit1.html", {"author": author})

WebBooks/catalog/templates/catalog/author_list.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Список авторов в БД</h1>
{% if author_list %}
    {% for author in author_list.all %}
    <p>{{ author.first_name }}  {{ author.last_name }}</p>
    {% endfor %}
{% else %}
<p>В базе данных нет авторов</p>
{% endif %}
{% endblock content %}

WebBooks/catalog/templates/catalog/authors_add.html
{% extends 'base_generic.html' %}

{% block content %}
<h3>Список авторов в БД</h3>
<table>
    <thead>
        <th>Id</th><th>----Имя----</th>
        <th>Фамилия</th><th></th>
    </thead>
    {% if author %}
        {% for author in author.all %}
        <tr>
            <td>{{ author.id }}</td>
            <td>{{ author.first_name }}</td>
            <td>{{ author.last_name }}</td>
            <td><a href="edit1/{{ author.id }}">Изменить</a>, 
            <a href="delete/{{ author.id }}">Удалить</a></td>
        </tr>
        {% endfor %}
    {% endif %}
</table>

<h3>Добавить в БД автора книги</h3>
<form action="/catalog/create/" method="POST">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" value="Сохранить">

</form>
{% endblock content %}

WebBooks/catalog/templates/catalog/book_detail.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Название книги: {{ book.title }}</h1>

<p><strong>Жанр: </strong>{{ book.genre }}</p>
<p><strong>Аннотация: </strong>{{ book.summary }}</p>
<p><strong>ISBN: </strong>{{ book.isbn }}</p>
<p><strong>Язык: </strong>{{ book.language }}</p>
{% for author in book.author.all  %}
<p><strong>Автор:</strong><a href=""> {{ author.first_name }} {{ author.last_name }}</p></a>
{% endfor %}
<div style="margin-left:20px;margin-top:20px">
    <h4>Количество экземпляров книг в БД</h4>
    {% for copy in book.bookinstance_set.all %}
    <hr><p class="{% if copy.status.id == 1 %} text-success
    {% elif copy.status.id == 2 %} text-danger 
    {% else %} text-warning {% endif %}"> {{ copy.status }}</p>
    <p><strong>Издательство</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Инвентарный номер: </strong>{{ copy.id }}</p>
    <p><strong>Статус экземпляра книги в БД: </strong>{{copy.status}}</p>
    {% endfor %}
</div>

{% endblock content %}

WebBooks/catalog/templates/catalog/book_list.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Список книг в БД</h1>
{% if book_list %}
<ul>
    {% for book in book_list %}
    <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> {{book.genre}} 
    </li>
    {% endfor %}

</ul>
{% else %}
<p>В базе нет книг</p>
{% endif %}
{% endblock content %}

WebBooks/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Взятые книги</h1>

{% if bookinstance_list %}
    <ul>
        {% for bookinst in bookinstance_list %}
        <li class="{% if bookinst.is_overdue %} text-danger {% endif %}">
            <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a>
            ({{ bookinst.due_back }})
        </li>
        {% endfor %}

    </ul>
{% else %}
    <p>Нет книг со статусом в ЗАКАЗЕ.</p>
{% endif %}
{% endblock content %}

WebBooks/catalog/templates/catalog/edit1.html
{% extends 'base_generic.html' %}

{% block content %}
<h3>Список авторов в БД</h3>
<h4>{{ author.first_name }} {{ author.last_name }}</h4>

<form method="POST">
    {% csrf_token %}
    <p><label>Измените имя</label><br>
        <input type="text" name="first_name" value="{{ author.first_name }}" />
    </p>
    <p><label>Измените фамилию</label><br>
        <input type="text" name="last_name" value="{{ author.last_name }}" />
    </p>
    <p><label>Измените дату рождения</label><br>
        <input type="date" name="date_of_birth" value="{{ author.date_of_birth }}" />
    </p>
    <p><label>Измените дату смерти</label><br>
        <input type="date" name="date_of_death" value="{{ author.date_of_death }}" />
    </p>
    <input type="submit" value="Сохранить">
</form>
{% endblock content %}

WebBooks/catalog/templates/catalog/index.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Главная страница</h1>
<p>
    Добро пожаловать в <em> Мир книг</em>, Это очень простой
    веб-сайт, написанный на Django. Разработан на Python
    в качестве учебного примера с использованием vs code.
</p>
<h2>Динамический контент</h2>
<p>База данных сайта Мир книг содержит следующее количество записей:</p>
<ul>
    <li><strong>Количестко книг: </strong> {{ num_books }}</li>
    <li><strong>Количество экземпляров книг: </strong>{{ num_instances }}</li>
    <li><strong>Koличecтвo экземпляров книг в заказе: </strong>{{ num_instances_available }}</li>
    <li><strong>Koличecтвo авторов книг: </strong>{{ num_authors }}</li>
</ul>
<p>Количество посещений данной страницы - {{num_visits}}</p>
{% endblock content %}